version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_DATABASE: matematicnomodeliranje
      MARIADB_ALLOW_EMPTY_PASSWORD: "yes" 
    volumes:
      - ./matematicnomodeliranje.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env